### PR TITLE
setup source files directory changed

### PR DESCRIPTION
**Pull request by pkdash**

### CODE REVIEW

**Comment by pkdash** [comment]
@nazmussazib Please review this small change  and +1 it.

**Comment by pkdash** [comment]
@nazmussazib Can you review this small change and let me know if I can merge to develop.

**Comment by pkdash** [comment]
@nazmussazib may not have time to review this as hs is leaving soon. @dtarb Can you review this so that I can merge.

**Comment by dtarb** [comment]
+1

**Pull request merged**
