### PR TITLE
improve CMakeLists.txt

### PR DESCRIPTION
**Pull request by alexbruy**
This improves readability and formatting of the CMakeLists.txt and also adds some checks:
 - check if MPI available at the configure stage
 - formatting fixes
 - cleanup

### CODE REVIEW

**Comment by alexbruy** [comment]
Maybe this also should be applied to single-file version too, but I can't find repo with it

**Comment by alexbruy** [comment]
Oh, just found that new tools gagewatershed, twi and setgtthreshold are not compiled because they are not listed in CMakeLists.txt. So I updated this pull-request with new commit to fix this.

**Comment by dtarb** [comment]
@ahmetartu with the changes you have made to Cmake and the makefile, is this pull request still relevant.  It was written for the old multifile version which is now superceded.  Can you please look at the CmakeLists.txt that @alexbruy added.  I do not think you should try merge it as there are conflicts, just incorporate anything that is relevant then close this pull request.

**Comment by ahmetartu** [comment]
I think this pull request is no longer relevant with the recent changes we made on CMakeLists.txt file. Closing it.

**Pull request closed without merging**
